#!/usr/bin/env python3
"""Build a clean production .env for Hostinger deploy (single source of truth)."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
SOURCE_ENV = PROJECT_ROOT / ".env"
PRODUCTION_ENV = PROJECT_ROOT / ".env.production"
PATCH_SCRIPT = SCRIPT_DIR / "patch-production-env.py"

SKIP_KEYS = {
    "HOSTINGER_API_TOKEN",
    "HOSTINGER_API_BASE_URI",
    "HOSTINGER_API_VERIFY_SSL",
}


def parse_env(content: str) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, raw = stripped.partition("=")
        key = key.strip()
        value = raw.strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1].replace('\\"', '"')
        elif value.startswith("'") and value.endswith("'"):
            value = value[1:-1]
        entries.append((key, value))
    return entries


def format_value(value: str) -> str:
    if any(c in value for c in " #\t\n\r\"'"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def load_patched() -> list[tuple[str, str]]:
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".env", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(SOURCE_ENV.read_text(encoding="utf-8"))
        tmp_path = tmp.name

    result = subprocess.run(
        [sys.executable, str(PATCH_SCRIPT), tmp_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr or result.stdout or "patch failed")

    entries = parse_env(Path(tmp_path).read_text(encoding="utf-8"))
    Path(tmp_path).unlink(missing_ok=True)

    if PRODUCTION_ENV.is_file():
        prod = dict(parse_env(PRODUCTION_ENV.read_text(encoding="utf-8")))
        merged: list[tuple[str, str]] = []
        seen: set[str] = set()
        for key, value in entries:
            if key in prod:
                merged.append((key, prod[key]))
            else:
                merged.append((key, value))
            seen.add(key)
        for key, value in prod.items():
            if key not in seen:
                merged.append((key, value))
        return merged

    return entries


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: create-production-env.py <output.env>", file=sys.stderr)
        return 1

    if not SOURCE_ENV.is_file():
        print(f"Missing {SOURCE_ENV}", file=sys.stderr)
        return 1
    if not PRODUCTION_ENV.is_file():
        print(
            f"Warning: {PRODUCTION_ENV} missing — deploy userà DATABASE_URL da .env (dev locale?)",
            file=sys.stderr,
        )

    out_path = Path(sys.argv[1])
    entries = load_patched()

    lines = [
        "# Production env — generated by deploy/create-production-env.py",
        "# Unica fonte env sul server (non importare anche in hPanel)",
        "",
    ]

    seen: set[str] = set()
    kept = 0
    for key, value in entries:
        if key in SKIP_KEYS or key in seen:
            continue
        seen.add(key)
        if value == "":
            continue
        lines.append(f"{key}={format_value(value)}")
        kept += 1

    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({kept} vars, empty keys omitted)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
