export type PlatformServiceStatus = "active" | "coming_soon";

export interface PlatformNavItem {
  id: string;
  label: string;
  roles?: string[];
}

export interface PlatformServiceConfig {
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  gradient: string;
  url: string;
  status: PlatformServiceStatus;
  badge?: string;
  moduleKey?: string;
  nav: PlatformNavItem[];
  roles?: string[];
}

export const PLATFORM_SERVICES: PlatformServiceConfig[] = [
  {
    slug: "operations",
    name: "Centrale Operativa",
    description: "Dashboard operativa con KPI, alert e riepilogo attività in tempo reale.",
    icon: "Dashboard",
    color: "#6366f1",
    gradient: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
    url: "/services/operations",
    status: "active",
    badge: "Hub",
    moduleKey: "operations",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "kpi", label: "KPI" },
      { id: "alert", label: "Alert" },
    ],
  },
  {
    slug: "business",
    name: "Business",
    description: "CRM e gestionale commerciale. Clienti, lead, pipeline e attività.",
    icon: "BusinessCenter",
    color: "#8b5cf6",
    gradient: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
    url: "/business",
    status: "active",
    nav: [],
  },
  {
    slug: "tickets",
    name: "Ticket & Assistenza",
    description: "Gestione ticket, SLA, messaggistica e canali di supporto.",
    icon: "ConfirmationNumber",
    color: "#0ea5e9",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #06b6d4 100%)",
    url: "/services/tickets",
    status: "active",
    moduleKey: "tickets",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Ticket" },
      { id: "aperti", label: "Aperti" },
      { id: "urgenti", label: "Urgenti" },
      { id: "in_lavorazione", label: "In lavorazione" },
      { id: "sla", label: "SLA" },
      { id: "canali", label: "Canali" },
      { id: "report", label: "Report" },
    ],
  },
  {
    slug: "appuntamenti",
    name: "Appuntamenti",
    description: "Agenda appuntamenti, prenotazioni e calendario servizi.",
    icon: "Event",
    color: "#10b981",
    gradient: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    url: "/services/appuntamenti",
    status: "active",
    moduleKey: "appuntamenti",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Appuntamenti" },
      { id: "calendario", label: "Calendario" },
    ],
  },
  {
    slug: "caf-patronato",
    name: "CAF & Patronato",
    description: "Pratiche fiscali, patronato, dichiarazioni e invii.",
    icon: "Description",
    color: "#f59e0b",
    gradient: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    url: "/services/caf-patronato",
    status: "active",
    moduleKey: "caf-patronato",
    roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "OPERATORE", "PATRONATO"],
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Pratiche" },
      { id: "caf", label: "CAF" },
      { id: "patronato", label: "Patronato" },
    ],
  },
  {
    slug: "entrate-uscite",
    name: "Entrate & Uscite",
    description: "Movimenti di cassa, incassi, pagamenti e scadenze.",
    icon: "Payments",
    color: "#22c55e",
    gradient: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
    url: "/services/entrate-uscite",
    status: "active",
    moduleKey: "entrate-uscite",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "giornata", label: "Giornata cassa" },
      { id: "nuovo", label: "Nuovo" },
      { id: "elenco", label: "Movimenti" },
      { id: "entrate", label: "Entrate" },
      { id: "uscite", label: "Uscite" },
      { id: "scadenze", label: "Scadenze" },
      { id: "listino", label: "Listino" },
      { id: "report", label: "Report" },
    ],
  },
  {
    slug: "energia",
    name: "Energia",
    description: "Contratti luce/gas, POD/PDR e attivazioni forniture.",
    icon: "Bolt",
    color: "#eab308",
    gradient: "linear-gradient(135deg, #eab308 0%, #ca8a04 100%)",
    url: "/services/energia",
    status: "active",
    moduleKey: "energia",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Contratti" },
      { id: "promemoria", label: "Promemoria" },
    ],
  },
  {
    slug: "anpr",
    name: "ANPR",
    description: "Richieste anagrafe nazionale, certificati e appuntamenti.",
    icon: "Badge",
    color: "#3b82f6",
    gradient: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    url: "/services/anpr",
    status: "active",
    moduleKey: "anpr",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Richieste" },
    ],
  },
  {
    slug: "cie",
    name: "CIE",
    description: "Prenotazioni e gestione Carta d'Identità Elettronica.",
    icon: "CreditCard",
    color: "#06b6d4",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)",
    url: "/services/cie",
    status: "active",
    moduleKey: "cie",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Prenotazioni" },
    ],
  },
  {
    slug: "visure-cr",
    name: "Visure & CR",
    description: "Visure camerali, catastali e certificati del registro.",
    icon: "FindInPage",
    color: "#64748b",
    gradient: "linear-gradient(135deg, #64748b 0%, #475569 100%)",
    url: "/services/visure-cr",
    status: "active",
    moduleKey: "visure-cr",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Pratiche" },
    ],
  },
  {
    slug: "brt",
    name: "BRT Spedizioni",
    description: "Spedizioni BRT, tracking e gestione colli.",
    icon: "LocalShipping",
    color: "#ef4444",
    gradient: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    url: "/services/brt",
    status: "active",
    moduleKey: "brt",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Spedizioni" },
      { id: "destinatari", label: "Destinatari" },
      { id: "log", label: "Log" },
    ],
  },
  {
    slug: "logistica",
    name: "Logistica & Ritiri",
    description: "Pacchi in attesa, ritiri e gestione magazzino.",
    icon: "Inventory2",
    color: "#f97316",
    gradient: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
    url: "/services/logistica",
    status: "active",
    moduleKey: "logistica",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Pacchi" },
      { id: "sedi", label: "Sedi ritiro" },
      { id: "notifiche", label: "Notifiche" },
    ],
  },
  {
    slug: "marketing",
    name: "Email Marketing",
    description: "Campagne email, iscritti, template e invii.",
    icon: "Campaign",
    color: "#ec4899",
    gradient: "linear-gradient(135deg, #ec4899 0%, #db2777 100%)",
    url: "/services/marketing",
    status: "active",
    moduleKey: "marketing",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "iscritti", label: "Iscritti" },
      { id: "campagne", label: "Campagne" },
    ],
  },
  {
    slug: "fedelta",
    name: "Programma Fedeltà",
    description: "Punti fedeltà, premi e movimenti clienti.",
    icon: "Loyalty",
    color: "#14b8a6",
    gradient: "linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)",
    url: "/services/fedelta",
    status: "active",
    moduleKey: "fedelta",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Movimenti" },
      { id: "saldi", label: "Saldi clienti" },
      { id: "premi", label: "Catalogo premi" },
    ],
  },
  {
    slug: "curriculum",
    name: "Curriculum",
    description: "Gestione CV, bozze e consegne ai clienti.",
    icon: "Work",
    color: "#6366f1",
    gradient: "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
    url: "/services/curriculum",
    status: "active",
    moduleKey: "curriculum",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Curriculum" },
      { id: "editor", label: "Editor CV" },
    ],
  },
  {
    slug: "aci",
    name: "ACI / Motorizzazione",
    description: "Pratiche ACI, targa, passaggio proprietà e visure.",
    icon: "DirectionsCar",
    color: "#78716c",
    gradient: "linear-gradient(135deg, #78716c 0%, #57534e 100%)",
    url: "/services/aci",
    status: "active",
    moduleKey: "aci",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Pratiche" },
    ],
  },
  {
    slug: "telegrammi",
    name: "Telegrammi",
    description: "Invio telegrammi, coda invii e storico.",
    icon: "Telegram",
    color: "#0284c7",
    gradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    url: "/services/telegrammi",
    status: "active",
    moduleKey: "telegrammi",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Telegrammi" },
    ],
  },
  {
    slug: "posta-telematica",
    name: "Posta Telematica",
    description: "Invii PEC ed email per cliente, ricevute PDF e tracciamento consegna (casella da .env).",
    icon: "MarkEmailRead",
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)",
    url: "/services/posta-telematica",
    status: "active",
    moduleKey: "posta-telematica",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "invio", label: "Nuovo invio" },
      { id: "storico", label: "Storico invii" },
      { id: "inbox", label: "Posta in arrivo" },
    ],
  },
  {
    slug: "express",
    name: "Express",
    description: "Vendite rapide telefoniche, offerte operatori, stock SIM e POS integrato con cassa.",
    icon: "FlashOn",
    color: "#eab308",
    gradient: "linear-gradient(135deg, #eab308 0%, #ca8a04 100%)",
    url: "/services/express",
    status: "active",
    moduleKey: "express",
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "pos", label: "Nuova vendita" },
      { id: "vendite", label: "Storico vendite" },
      { id: "magazzino", label: "Magazzino SIM" },
      { id: "offerte", label: "Listini" },
      { id: "confronto", label: "Confronto offerte" },
      { id: "prodotti", label: "Prodotti" },
      { id: "richieste", label: "Richieste" },
      { id: "portale", label: "Portale clienti" },
      { id: "report", label: "Report" },
      { id: "impostazioni", label: "Impostazioni" },
    ],
  },
  {
    slug: "opportunities",
    name: "Opportunità",
    description: "Pipeline opportunità per collaboratori e partner commerciali.",
    icon: "TrendingUp",
    color: "#8b5cf6",
    gradient: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
    url: "/services/opportunities",
    status: "active",
    moduleKey: "opportunities",
    roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "COLLABORATORE"],
    nav: [
      { id: "dashboard", label: "Dashboard" },
      { id: "elenco", label: "Elenco" },
      { id: "nuovo", label: "Nuovo" },
      { id: "pipeline", label: "Pipeline" },
      { id: "verifica", label: "In verifica" },
      { id: "documenti", label: "Documenti" },
      { id: "firma", label: "Firma OTP" },
      { id: "telefonia", label: "Telefonia" },
      { id: "luce", label: "Luce" },
      { id: "gas", label: "Gas" },
      { id: "classifica", label: "Classifica" },
      { id: "collaboratori", label: "Collaboratori", roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "OPERATORE"] },
      { id: "catalogo", label: "Catalogo", roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "OPERATORE"] },
      { id: "report", label: "Report" },
    ],
  },
  {
    slug: "portale",
    name: "Portale Cliente",
    description: "Area riservata clienti: ticket, pratiche e documenti.",
    icon: "AccountCircle",
    color: "#6366f1",
    gradient: "linear-gradient(135deg, #6366f1 0%, #818cf8 100%)",
    url: "/portale",
    status: "active",
    roles: ["SUPER_ADMIN", "ADMIN", "CLIENTE"],
    nav: [],
  },
];

export function getPlatformService(slug: string) {
  return PLATFORM_SERVICES.find((s) => s.slug === slug);
}

export function getActivePlatformServices(role?: string) {
  return PLATFORM_SERVICES.filter((s) => {
    if (s.status !== "active") return false;
    if (!s.roles || !role) return true;
    return s.roles.includes(role);
  });
}
